spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
 client:
   fetch-registry: false
   register-with-eureka: false
 server:
   initial-capacity-of-response-cache: 5000
   wait-time-in-ms-when-sync-empty: 5

