
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: pouria
    password: 9776Pl_GSP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: product



server:
  port: 9091


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
